version: "3.8"
services:
  crawler:
    build: .
    depends_on:
      db:
        condition: service_healthy
  db:
    build: ./src/database/
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER",  "-d", "$POSTGRES_DB"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always
