version: "3.8"
services:
  crawler:
    build: .
    depends_on:
      db:
        condition: service_healthy
  db:
    image: "postgres" 
    build: ./src/database/
    env_file:
      - database.env # PG configure
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER",  "-d", "$POSTGRES_DB"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always
